from __future__ import annotations

import argparse
import json
import re
import shutil
import tempfile
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_DIR = ROOT / "contracts" / "schema"
PY_OUT_DIR = ROOT / "contracts" / "gen" / "python"
FIXTURE_DIR = ROOT / "contracts" / "fixtures"

HEADER = [
    "# GENERATED by tools/codegen.py from contracts/schema/ -- DO NOT EDIT",
    "# Edit schema and rerun `python tools/task.py codegen`.",
    "",
]

PAYLOAD_FILES = [
    "hello",
    "hello_ack",
    "heartbeat",
    "heartbeat_ack",
    "bar",
    "state",
    "intent",
    "intent_ack",
    "exec_report",
    "risk_directive",
    "config_update",
    "error",
]

TYPE_TO_PAYLOAD = {
    "HELLO": "HelloPayload",
    "HELLO_ACK": "HelloAckPayload",
    "HEARTBEAT": "HeartbeatPayload",
    "HEARTBEAT_ACK": "HeartbeatAckPayload",
    "BAR": "BarPayload",
    "STATE": "StatePayload",
    "INTENT": "IntentPayload",
    "INTENT_ACK": "IntentAckPayload",
    "EXEC_REPORT": "ExecReportPayload",
    "RISK_DIRECTIVE": "RiskDirectivePayload",
    "CONFIG_UPDATE": "ConfigUpdatePayload",
    "ERROR": "ErrorPayload",
}

ULID = "01J8X4K2P9QZ7M3N4R5T6V7W8X"
SESSION_ID = "acct-8123456-EURUSD.iux-H1"
TS = "2026-07-26T14:30:00Z"
TS_MS = "2026-07-26T14:30:00.412Z"
SYMBOL = "EURUSD.iux"


@dataclass(frozen=True)
class FieldSpec:
    name: str
    annotation: str
    required: bool
    comment: str | None


@dataclass
class ClassSpec:
    name: str
    schema: dict[str, Any]
    fields: list[FieldSpec]
    comment: str | None
    extra: str


class PythonGenerator:
    def __init__(self, schemas: dict[str, dict[str, Any]]) -> None:
        self.schemas = schemas
        self.classes: OrderedDict[str, ClassSpec] = OrderedDict()
        self.enums: OrderedDict[str, list[Any]] = OrderedDict()

    def generate(self) -> str:
        self._add_common_classes()
        for name in PAYLOAD_FILES:
            self._add_object(
                self._payload_class_name(name), self.schemas[f"{name}.json"], f"{name}.json"
            )
        self._add_object("FarmEnvelope", self.schemas["envelope.json"], "envelope.json")

        lines = [*HEADER]
        lines.extend(
            [
                "from __future__ import annotations",
                "",
                "from enum import Enum",
                "from typing import Annotated, Any, Dict, List, Literal, Optional",
                "",
                "from pydantic import BaseModel, ConfigDict, Field",
                "",
                "",
            ]
        )

        for enum_name, values in self.enums.items():
            lines.append(f"class {enum_name}(str, Enum):")
            for value in values:
                if value is None:
                    continue
                lines.append(f"    {self._enum_member(str(value))} = {value!r}")
            lines.append("")
            lines.append("")

        for cls in self.classes.values():
            if cls.comment:
                lines.append("# INVARIANT (must be validated outside generated schema models):")
                for line in cls.comment.splitlines():
                    lines.append(f"#   {line}")
            lines.append(f"class {cls.name}(BaseModel):")
            lines.append(f'    model_config = ConfigDict(extra="{cls.extra}")')
            lines.append("")
            if not cls.fields:
                lines.append("    pass")
            for field in cls.fields:
                if field.comment:
                    for line in field.comment.splitlines():
                        lines.append(f"    # {line}")
                default = "" if field.required else " = None"
                lines.append(f"    {field.name}: {field.annotation}{default}")
            lines.append("")
            lines.append("")

        lines.append("PAYLOAD_MODELS: Dict[str, type[BaseModel]] = {")
        for msg_type in self.schemas["envelope.json"]["properties"]["type"]["enum"]:
            lines.append(f"    {msg_type!r}: {TYPE_TO_PAYLOAD[msg_type]},")
        lines.append("}")
        lines.append("")
        for class_name in self.classes:
            lines.append(f"{class_name}.model_rebuild()")
        lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def public_symbols(self) -> list[str]:
        return ["PAYLOAD_MODELS", *sorted([*self.enums.keys(), *self.classes.keys()])]

    def _add_common_classes(self) -> None:
        defs = self.schemas["common.json"]["$defs"]
        for name in ["account_info", "symbol_spec", "broker_time_info", "local_limits"]:
            self._add_object(self._class_name(name), defs[name], "common.json")

    def _add_object(self, class_name: str, schema: dict[str, Any], source_file: str) -> str:
        if class_name in self.classes:
            return class_name
        required = list(schema.get("required", []))
        properties = schema.get("properties", {})
        ordered_names = [name for name in required if name in properties]
        ordered_names.extend(sorted(name for name in properties if name not in required))

        fields: list[FieldSpec] = []
        self.classes[class_name] = ClassSpec(
            name=class_name,
            schema=schema,
            fields=fields,
            comment=schema.get("$comment"),
            extra="forbid" if class_name == "ConfigUpdateSettings" else "ignore",
        )
        for field_name in ordered_names:
            field_schema = properties[field_name]
            annotation = self._annotation(
                field_schema, f"{class_name}{self._class_name(field_name)}", source_file
            )
            if field_name == "payload" and class_name == "FarmEnvelope":
                annotation = "Dict[str, Any]"
            if field_name not in required:
                annotation = self._optional_annotation(annotation)
            if not field_name.isidentifier():
                raise ValueError(f"unsupported field name: {field_name}")
            fields.append(
                FieldSpec(
                    name=field_name,
                    annotation=annotation,
                    required=field_name in required,
                    comment=field_schema.get("description"),
                )
            )
        return class_name

    def _annotation(self, schema: dict[str, Any], name_hint: str, source_file: str) -> str:
        resolved = self._resolve_ref(schema, source_file)
        if "oneOf" in resolved:
            non_null = [item for item in resolved["oneOf"] if item.get("type") != "null"]
            has_null = len(non_null) != len(resolved["oneOf"])
            if len(non_null) != 1 or not has_null:
                raise ValueError(f"unsupported oneOf in {name_hint}")
            return f"Optional[{self._annotation(non_null[0], name_hint, source_file)}]"
        if "const" in resolved:
            return f"Literal[{resolved['const']!r}]"
        if "enum" in resolved:
            values = list(resolved["enum"])
            has_null = None in values
            enum_values = [value for value in values if value is not None]
            enum_name = self._enum_name(name_hint)
            if enum_name not in self.enums:
                self.enums[enum_name] = enum_values
            return f"Optional[{enum_name}]" if has_null else enum_name

        schema_type = resolved.get("type")
        if isinstance(schema_type, list):
            non_null_types = [item for item in schema_type if item != "null"]
            if len(non_null_types) != 1:
                raise ValueError(f"unsupported union type in {name_hint}: {schema_type}")
            inner = dict(resolved)
            inner["type"] = non_null_types[0]
            return f"Optional[{self._annotation(inner, name_hint, source_file)}]"
        if schema_type == "string":
            return self._annotated_scalar("str", resolved)
        if schema_type == "integer":
            return self._annotated_scalar("int", resolved)
        if schema_type == "number":
            return self._annotated_scalar("float", resolved)
        if schema_type == "boolean":
            return "bool"
        if schema_type == "array":
            return f"List[{self._annotation(resolved['items'], name_hint + 'Item', source_file)}]"
        if schema_type == "object":
            properties = resolved.get("properties")
            if properties:
                object_name = (
                    "ConfigUpdateSettings"
                    if name_hint == "ConfigUpdatePayloadSettings"
                    else name_hint
                )
                return self._add_object(object_name, resolved, source_file)
            additional = resolved.get("additionalProperties")
            if isinstance(additional, dict):
                value_type = self._annotation(additional, name_hint + "Value", source_file)
            else:
                value_type = "Any"
            key_type = "str"
            property_names = resolved.get("propertyNames")
            if isinstance(property_names, dict):
                key_type = self._annotation(property_names, name_hint + "Key", source_file)
            return f"Dict[{key_type}, {value_type}]"
        raise ValueError(f"unsupported schema in {name_hint}: {resolved}")

    def _resolve_ref(self, schema: dict[str, Any], source_file: str) -> dict[str, Any]:
        if "$ref" not in schema:
            return schema
        ref = schema["$ref"]
        filename, _, pointer = ref.partition("#/")
        if not filename:
            filename = source_file
        target: Any = self.schemas[filename]
        for part in pointer.split("/"):
            target = target[part]
        merged = dict(target)
        for key, value in schema.items():
            if key != "$ref":
                merged[key] = value
        return merged

    def _annotated_scalar(self, base: str, schema: dict[str, Any]) -> str:
        args: list[str] = []
        mapping = {
            "minimum": "ge",
            "maximum": "le",
            "exclusiveMinimum": "gt",
            "exclusiveMaximum": "lt",
            "minLength": "min_length",
            "maxLength": "max_length",
            "pattern": "pattern",
        }
        for src, dst in mapping.items():
            if src in schema:
                args.append(f"{dst}={schema[src]!r}")
        if not args:
            return base
        return f"Annotated[{base}, Field({', '.join(args)})]"

    @staticmethod
    def _optional_annotation(annotation: str) -> str:
        if annotation.startswith("Optional["):
            return annotation
        return f"Optional[{annotation}]"

    @staticmethod
    def _class_name(raw: str) -> str:
        return "".join(part.capitalize() for part in re.split(r"[^A-Za-z0-9]+", raw) if part)

    @staticmethod
    def _payload_class_name(raw: str) -> str:
        return PythonGenerator._class_name(raw) + "Payload"

    @staticmethod
    def _enum_name(raw: str) -> str:
        if raw.endswith("Enum"):
            return raw
        return raw + "Enum"

    @staticmethod
    def _enum_member(value: str) -> str:
        name = re.sub(r"[^A-Za-z0-9]+", "_", value).upper().strip("_")
        if not name or name[0].isdigit():
            name = "V_" + name
        return name


def load_schemas() -> dict[str, dict[str, Any]]:
    return {
        path.name: json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(SCHEMA_DIR.glob("*.json"))
    }


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", newline="\n", delete=False, dir=path.parent
    ) as fh:
        fh.write(content)
        tmp = Path(fh.name)
    tmp.replace(path)


def sample_for(
    schema: dict[str, Any],
    schemas: dict[str, dict[str, Any]],
    *,
    minimal: bool,
    source_file: str = "common.json",
) -> Any:
    schema = resolve_ref(schema, schemas, source_file)
    if "oneOf" in schema:
        non_null = [item for item in schema["oneOf"] if item.get("type") != "null"]
        return (
            sample_for(non_null[0], schemas, minimal=minimal, source_file=source_file)
            if non_null
            else None
        )
    if "const" in schema:
        return schema["const"]
    if "enum" in schema:
        return next(value for value in schema["enum"] if value is not None)
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        non_null = [item for item in schema_type if item != "null"]
        if "null" in schema_type and minimal:
            return None
        return sample_for(
            {**schema, "type": non_null[0]},
            schemas,
            minimal=minimal,
            source_file=source_file,
        )
    if schema_type == "string":
        pattern = schema.get("pattern", "")
        if pattern == "^[0-9A-HJKMNP-TV-Z]{26}$":
            return ULID
        if pattern.startswith("^acct-"):
            return SESSION_ID
        if pattern.startswith("^[A-Z0-9]{3,15}"):
            return SYMBOL
        if pattern == "^[A-Z]{3}$":
            return "USD"
        if pattern == "^[0-9]+\\.[0-9]+\\.[0-9]+$":
            return "1.0.0"
        if pattern == "^[A-Z][A-Z0-9_]{2,63}$":
            return "BAD_REQUEST"
        if pattern.startswith("^[a-z0-9_]"):
            return "trend_v1"
        if pattern.startswith("^sha256:"):
            return "sha256:abcdef12"
        if "Z$" in pattern:
            return TS
        return "value"
    if schema_type == "integer":
        return max(1, int(schema.get("minimum", 1)))
    if schema_type == "number":
        minimum = schema.get("exclusiveMinimum", schema.get("minimum", 1.0))
        if minimum == 0:
            return 1.0
        if minimum < 0:
            return 0.0
        return float(minimum)
    if schema_type == "boolean":
        return True
    if schema_type == "array":
        if minimal:
            return []
        return [sample_for(schema["items"], schemas, minimal=minimal, source_file=source_file)]
    if schema_type == "object":
        props = schema.get("properties", {})
        required = list(schema.get("required", []))
        names = (
            required
            if minimal
            else [*required, *sorted(name for name in props if name not in required)]
        )
        if props:
            return {
                name: sample_for(props[name], schemas, minimal=minimal, source_file=source_file)
                for name in names
                if name in props
            }
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return {
                SYMBOL: sample_for(additional, schemas, minimal=minimal, source_file=source_file)
            }
        return {}
    raise ValueError(f"cannot make sample for schema: {schema}")


def resolve_ref(
    schema: dict[str, Any], schemas: dict[str, dict[str, Any]], source_file: str
) -> dict[str, Any]:
    if "$ref" not in schema:
        return schema
    filename, _, pointer = schema["$ref"].partition("#/")
    if not filename:
        filename = source_file
    target: Any = schemas[filename]
    for part in pointer.split("/"):
        target = target[part]
    merged = dict(target)
    for key, value in schema.items():
        if key != "$ref":
            merged[key] = value
    return merged


def envelope_for(msg_type: str, payload: dict[str, Any]) -> dict[str, Any]:
    return OrderedDict(
        [
            ("v", 1),
            ("type", msg_type),
            ("msg_id", ULID),
            ("session_id", SESSION_ID),
            ("ts_server", TS),
            ("ts_sent", TS_MS),
            ("payload", payload),
        ]
    )


def dumps_json(data: Any) -> str:
    return json.dumps(data, ensure_ascii=False, sort_keys=False, separators=(",", ":")) + "\n"


def write_fixtures(schemas: dict[str, dict[str, Any]]) -> None:
    if FIXTURE_DIR.exists():
        shutil.rmtree(FIXTURE_DIR)
    (FIXTURE_DIR / "invalid").mkdir(parents=True)
    for name in PAYLOAD_FILES:
        msg_type = name.upper()
        schema_file = f"{name}.json"
        payload = sample_for(schemas[schema_file], schemas, minimal=False, source_file=schema_file)
        minimal_payload = sample_for(
            schemas[schema_file], schemas, minimal=True, source_file=schema_file
        )
        extra_payload = dict(payload)
        extra_payload["x_forward_compat"] = "ignored"
        atomic_write(
            FIXTURE_DIR / f"{name}.valid.json", dumps_json(envelope_for(msg_type, payload))
        )
        atomic_write(
            FIXTURE_DIR / f"{name}.valid.min.json",
            dumps_json(envelope_for(msg_type, minimal_payload)),
        )
        atomic_write(
            FIXTURE_DIR / f"{name}.valid.extra.json",
            dumps_json(envelope_for(msg_type, extra_payload)),
        )

    invalid_cases: dict[str, dict[str, Any]] = {}
    base = envelope_for(
        "HELLO", sample_for(schemas["hello.json"], schemas, minimal=False, source_file="hello.json")
    )
    bad = dict(base)
    bad["msg_id"] = "202607261430000000"
    invalid_cases["envelope.msgid_18digits.json"] = bad
    bad = dict(base)
    bad["session_id"] = "acct-8123456-EURUSD.iux-PERIOD_H1"
    invalid_cases["envelope.session_period_prefix.json"] = bad
    bad = dict(base)
    bad["ts_server"] = "2026-07-26T14:30:00+07:00"
    invalid_cases["envelope.ts_offset_not_z.json"] = bad

    state = envelope_for(
        "STATE", sample_for(schemas["state.json"], schemas, minimal=False, source_file="state.json")
    )
    state["payload"]["positions"][0]["sl"] = 0
    invalid_cases["state.sl_zero.json"] = state
    state_bad_map = envelope_for(
        "STATE", sample_for(schemas["state.json"], schemas, minimal=False, source_file="state.json")
    )
    state_bad_map["payload"]["owned_net"] = {"PERIOD_H1": 0.2}
    invalid_cases["state.owned_net_bad_symbol_key.json"] = state_bad_map

    risk = envelope_for(
        "RISK_DIRECTIVE",
        sample_for(
            schemas["risk_directive.json"],
            schemas,
            minimal=False,
            source_file="risk_directive.json",
        ),
    )
    risk["payload"]["scale_factor"] = 1.5
    invalid_cases["risk_directive.scale_above_one.json"] = risk

    bar = envelope_for(
        "BAR", sample_for(schemas["bar.json"], schemas, minimal=False, source_file="bar.json")
    )
    bar["payload"]["is_final"] = False
    invalid_cases["bar.is_final_false.json"] = bar

    hello = envelope_for(
        "HELLO", sample_for(schemas["hello.json"], schemas, minimal=False, source_file="hello.json")
    )
    hello["payload"]["account"]["margin_mode"] = "retail_hedging"
    invalid_cases["hello.margin_mode_lowercase.json"] = hello

    config = envelope_for(
        "CONFIG_UPDATE",
        sample_for(
            schemas["config_update.json"], schemas, minimal=False, source_file="config_update.json"
        ),
    )
    config["payload"]["settings"]["max_lot_per_order"] = 0.5
    invalid_cases["config_update.unknown_setting.json"] = config

    for name, data in sorted(invalid_cases.items()):
        atomic_write(FIXTURE_DIR / "invalid" / name, dumps_json(data))


def write_python_models(schemas: dict[str, dict[str, Any]]) -> None:
    generator = PythonGenerator(schemas)
    content = generator.generate()
    atomic_write(PY_OUT_DIR / "models.py", content)
    symbols = generator.public_symbols()
    init = "\n".join(
        [
            "# GENERATED by tools/codegen.py from contracts/schema/ -- DO NOT EDIT",
            "# Edit schema and rerun `python tools/task.py codegen`.",
            "",
            "from .models import (",
            *[f"    {symbol}," for symbol in symbols],
            ")",
            "",
            "__all__ = [",
            *[f"    {symbol!r}," for symbol in symbols],
            "]",
            "",
        ]
    )
    atomic_write(PY_OUT_DIR / "__init__.py", init)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.parse_args(argv)
    schemas = load_schemas()
    write_python_models(schemas)
    write_fixtures(schemas)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
