from __future__ import annotations

# ruff: noqa: E402, E501, I001

import argparse
import json
import re
import sys
import tempfile
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from brain.common.canonical_json import dumps_canonical_json  # noqa: E402
from brain.common.registry import load_symbol_registry_data, validate_symbol_registry_data  # noqa: E402

SCHEMA_DIR = ROOT / "contracts" / "schema"
SYMBOLS_FILE = ROOT / "contracts" / "symbols.json"
PY_OUT_DIR = ROOT / "contracts" / "gen" / "python"
MQL5_OUT_DIR = ROOT / "contracts" / "gen" / "mql5"

HEADER = [
    "# GENERATED by tools/codegen.py from contracts/schema/ -- DO NOT EDIT",
    "# Edit schema and rerun `python tools/task.py codegen`.",
    "",
]

PAYLOAD_FILES = [
    "hello",
    "hello_ack",
    "heartbeat",
    "heartbeat_ack",
    "bar",
    "state",
    "intent",
    "intent_ack",
    "exec_report",
    "risk_directive",
    "config_update",
    "error",
]

TYPE_TO_PAYLOAD = {
    "HELLO": "HelloPayload",
    "HELLO_ACK": "HelloAckPayload",
    "HEARTBEAT": "HeartbeatPayload",
    "HEARTBEAT_ACK": "HeartbeatAckPayload",
    "BAR": "BarPayload",
    "STATE": "StatePayload",
    "INTENT": "IntentPayload",
    "INTENT_ACK": "IntentAckPayload",
    "EXEC_REPORT": "ExecReportPayload",
    "RISK_DIRECTIVE": "RiskDirectivePayload",
    "CONFIG_UPDATE": "ConfigUpdatePayload",
    "ERROR": "ErrorPayload",
}

MQL5_HEADER = [
    "// GENERATED by tools/codegen.py from contracts/schema/ -- DO NOT EDIT",
    "// Edit schema and rerun `python tools/task.py codegen`.",
    "",
]

SYMBOLS_PY_HEADER = [
    "# GENERATED by tools/codegen.py from contracts/symbols.json -- DO NOT EDIT",
    "# Edit contracts/symbols.json and rerun `python tools/task.py codegen`.",
    "",
]

SYMBOLS_MQL5_HEADER = [
    "// GENERATED by tools/codegen.py from contracts/symbols.json -- DO NOT EDIT",
    "// Edit contracts/symbols.json and rerun `python tools/task.py codegen`.",
    "",
]

SYMBOLS_PUBLIC = [
    "BROKER_TO_CANONICAL",
    "CANONICALS",
    "REGISTRY_VERSION",
    "CanonicalSymbol",
    "RiskProfile",
]

ULID = "01J8X4K2P9QZ7M3N4R5T6V7W8X"
SESSION_ID = "acct-8123456-EURUSD.iux-H1"
TS = "2026-07-26T14:30:00Z"
TS_MS = "2026-07-26T14:30:00.412Z"
SYMBOL = "EURUSD.iux"


@dataclass(frozen=True)
class FieldSpec:
    name: str
    annotation: str
    required: bool
    comment: str | None


@dataclass
class ClassSpec:
    name: str
    schema: dict[str, Any]
    fields: list[FieldSpec]
    comment: str | None
    extra: str


@dataclass(frozen=True)
class Mql5FieldSpec:
    name: str
    json_name: str
    kind: str
    mql_type: str
    required: bool
    nullable: bool
    comment: str | None
    item_kind: str | None = None
    item_type: str | None = None
    value_kind: str | None = None
    value_type: str | None = None


@dataclass
class Mql5StructSpec:
    name: str
    schema: dict[str, Any]
    fields: list[Mql5FieldSpec]
    comment: str | None
    is_payload: bool


class PythonGenerator:
    def __init__(self, schemas: dict[str, dict[str, Any]]) -> None:
        self.schemas = schemas
        self.classes: OrderedDict[str, ClassSpec] = OrderedDict()
        self.enums: OrderedDict[str, list[Any]] = OrderedDict()

    def generate(self) -> str:
        self._add_common_classes()
        for name in PAYLOAD_FILES:
            self._add_object(
                self._payload_class_name(name), self.schemas[f"{name}.json"], f"{name}.json"
            )
        self._add_object("FarmEnvelope", self.schemas["envelope.json"], "envelope.json")

        lines = [*HEADER]
        lines.extend(
            [
                "from __future__ import annotations",
                "",
                "from enum import Enum",
                "from typing import Annotated, Any, Dict, List, Literal, Optional",
                "",
                "from pydantic import BaseModel, ConfigDict, Field",
                "",
                "",
            ]
        )

        for enum_name, values in self.enums.items():
            lines.append(f"class {enum_name}(str, Enum):")
            for value in values:
                if value is None:
                    continue
                lines.append(f"    {self._enum_member(str(value))} = {value!r}")
            lines.append("")
            lines.append("")

        for cls in self.classes.values():
            if cls.comment:
                lines.append("# INVARIANT (must be validated outside generated schema models):")
                for line in cls.comment.splitlines():
                    lines.append(f"#   {line}")
            lines.append(f"class {cls.name}(BaseModel):")
            lines.append(f'    model_config = ConfigDict(extra="{cls.extra}")')
            lines.append("")
            if not cls.fields:
                lines.append("    pass")
            for field in cls.fields:
                if field.comment:
                    for line in field.comment.splitlines():
                        lines.append(f"    # {line}")
                default = "" if field.required else " = None"
                lines.append(f"    {field.name}: {field.annotation}{default}")
            lines.append("")
            lines.append("")

        lines.append("PAYLOAD_MODELS: Dict[str, type[BaseModel]] = {")
        for msg_type in self.schemas["envelope.json"]["properties"]["type"]["enum"]:
            lines.append(f"    {msg_type!r}: {TYPE_TO_PAYLOAD[msg_type]},")
        lines.append("}")
        lines.append("")
        for class_name in self.classes:
            lines.append(f"{class_name}.model_rebuild()")
        lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    def public_symbols(self) -> list[str]:
        return ["PAYLOAD_MODELS", *sorted([*self.enums.keys(), *self.classes.keys()])]

    def _add_common_classes(self) -> None:
        defs = self.schemas["common.json"]["$defs"]
        for name in ["account_info", "symbol_spec", "broker_time_info", "local_limits"]:
            self._add_object(self._class_name(name), defs[name], "common.json")

    def _add_object(self, class_name: str, schema: dict[str, Any], source_file: str) -> str:
        if class_name in self.classes:
            return class_name
        required = list(schema.get("required", []))
        properties = schema.get("properties", {})
        ordered_names = [name for name in required if name in properties]
        ordered_names.extend(sorted(name for name in properties if name not in required))

        fields: list[FieldSpec] = []
        self.classes[class_name] = ClassSpec(
            name=class_name,
            schema=schema,
            fields=fields,
            comment=schema.get("$comment"),
            extra="forbid" if class_name == "ConfigUpdateSettings" else "ignore",
        )
        for field_name in ordered_names:
            field_schema = properties[field_name]
            annotation = self._annotation(
                field_schema, f"{class_name}{self._class_name(field_name)}", source_file
            )
            if field_name == "payload" and class_name == "FarmEnvelope":
                annotation = "Dict[str, Any]"
            if field_name not in required:
                annotation = self._optional_annotation(annotation)
            if not field_name.isidentifier():
                raise ValueError(f"unsupported field name: {field_name}")
            fields.append(
                FieldSpec(
                    name=field_name,
                    annotation=annotation,
                    required=field_name in required,
                    comment=field_schema.get("description"),
                )
            )
        return class_name

    def _annotation(self, schema: dict[str, Any], name_hint: str, source_file: str) -> str:
        resolved = self._resolve_ref(schema, source_file)
        if "oneOf" in resolved:
            non_null = [item for item in resolved["oneOf"] if item.get("type") != "null"]
            has_null = len(non_null) != len(resolved["oneOf"])
            if len(non_null) != 1 or not has_null:
                raise ValueError(f"unsupported oneOf in {name_hint}")
            return f"Optional[{self._annotation(non_null[0], name_hint, source_file)}]"
        if "const" in resolved:
            return f"Literal[{resolved['const']!r}]"
        if "enum" in resolved:
            values = list(resolved["enum"])
            has_null = None in values
            enum_values = [value for value in values if value is not None]
            enum_name = self._enum_name(name_hint)
            if enum_name not in self.enums:
                self.enums[enum_name] = enum_values
            return f"Optional[{enum_name}]" if has_null else enum_name

        schema_type = resolved.get("type")
        if isinstance(schema_type, list):
            non_null_types = [item for item in schema_type if item != "null"]
            if len(non_null_types) != 1:
                raise ValueError(f"unsupported union type in {name_hint}: {schema_type}")
            inner = dict(resolved)
            inner["type"] = non_null_types[0]
            return f"Optional[{self._annotation(inner, name_hint, source_file)}]"
        if schema_type == "string":
            return self._annotated_scalar("str", resolved)
        if schema_type == "integer":
            return self._annotated_scalar("int", resolved)
        if schema_type == "number":
            return self._annotated_scalar("float", resolved)
        if schema_type == "boolean":
            return "bool"
        if schema_type == "array":
            return f"List[{self._annotation(resolved['items'], name_hint + 'Item', source_file)}]"
        if schema_type == "object":
            properties = resolved.get("properties")
            if properties:
                object_name = (
                    "ConfigUpdateSettings"
                    if name_hint == "ConfigUpdatePayloadSettings"
                    else name_hint
                )
                return self._add_object(object_name, resolved, source_file)
            additional = resolved.get("additionalProperties")
            if isinstance(additional, dict):
                value_type = self._annotation(additional, name_hint + "Value", source_file)
            else:
                value_type = "Any"
            key_type = "str"
            property_names = resolved.get("propertyNames")
            if isinstance(property_names, dict):
                key_type = self._annotation(property_names, name_hint + "Key", source_file)
            return f"Dict[{key_type}, {value_type}]"
        raise ValueError(f"unsupported schema in {name_hint}: {resolved}")

    def _resolve_ref(self, schema: dict[str, Any], source_file: str) -> dict[str, Any]:
        if "$ref" not in schema:
            return schema
        ref = schema["$ref"]
        filename, _, pointer = ref.partition("#/")
        if not filename:
            filename = source_file
        target: Any = self.schemas[filename]
        for part in pointer.split("/"):
            target = target[part]
        merged = dict(target)
        for key, value in schema.items():
            if key != "$ref":
                merged[key] = value
        return merged

    def _annotated_scalar(self, base: str, schema: dict[str, Any]) -> str:
        args: list[str] = []
        mapping = {
            "minimum": "ge",
            "maximum": "le",
            "exclusiveMinimum": "gt",
            "exclusiveMaximum": "lt",
            "minLength": "min_length",
            "maxLength": "max_length",
            "pattern": "pattern",
        }
        for src, dst in mapping.items():
            if src in schema:
                args.append(f"{dst}={schema[src]!r}")
        if not args:
            return base
        return f"Annotated[{base}, Field({', '.join(args)})]"

    @staticmethod
    def _optional_annotation(annotation: str) -> str:
        if annotation.startswith("Optional["):
            return annotation
        return f"Optional[{annotation}]"

    @staticmethod
    def _class_name(raw: str) -> str:
        return "".join(part.capitalize() for part in re.split(r"[^A-Za-z0-9]+", raw) if part)

    @staticmethod
    def _payload_class_name(raw: str) -> str:
        return PythonGenerator._class_name(raw) + "Payload"

    @staticmethod
    def _enum_name(raw: str) -> str:
        if raw.endswith("Enum"):
            return raw
        return raw + "Enum"

    @staticmethod
    def _enum_member(value: str) -> str:
        name = re.sub(r"[^A-Za-z0-9]+", "_", value).upper().strip("_")
        if not name or name[0].isdigit():
            name = "V_" + name
        return name


class Mql5Generator:
    def __init__(self, schemas: dict[str, dict[str, Any]]) -> None:
        self.schemas = schemas
        self.structs: OrderedDict[str, Mql5StructSpec] = OrderedDict()
        self.enums: OrderedDict[str, list[Any]] = OrderedDict()

    def generate(self) -> str:
        msg_types = list(self.schemas["envelope.json"]["properties"]["type"]["enum"])
        lines = [*MQL5_HEADER]
        lines.extend(
            [
                "#ifndef FARM_MESSAGES_MQH",
                "#define FARM_MESSAGES_MQH",
                "",
                "#include <Farm/JsonCore.mqh>",
                "",
                "enum ENUM_FARM_MSG_TYPE",
                "{",
            ]
        )
        for msg_type in msg_types:
            lines.append(f"   FARM_MSG_{msg_type},")
        self._collect_payload_structs()
        lines.extend(
            [
                "   FARM_MSG_UNKNOWN",
                "};",
                "",
            ]
        )
        lines.extend(self._emit_enums())
        lines.extend(
            [
                "struct FarmEnvelope",
                "{",
                "   int                v;",
                "   ENUM_FARM_MSG_TYPE type;",
                "   string             type_raw;",
                "   string             msg_id;",
                "   string             session_id;",
                "   string             ts_server;",
                "   string             ts_sent;",
                "   string             payload_json;",
                "};",
                "",
            ]
        )
        lines.extend(self._emit_structs())
        lines.extend(self._helpers(msg_types))
        lines.append("#endif")
        return "\n".join(lines).rstrip() + "\n"

    def _collect_payload_structs(self) -> None:
        self.structs.clear()
        self.enums.clear()
        for schema_name in PAYLOAD_FILES:
            struct_name = f"Farm{PythonGenerator._payload_class_name(schema_name)}"
            self._add_struct(struct_name, self.schemas[f"{schema_name}.json"], f"{schema_name}.json", True)

    def _add_struct(
        self, struct_name: str, schema: dict[str, Any], source_file: str, is_payload: bool
    ) -> str:
        schema = resolve_ref(schema, self.schemas, source_file)
        if struct_name in self.structs:
            return struct_name
        required = list(schema.get("required", []))
        properties = schema.get("properties", {})
        names = [name for name in required if name in properties]
        names.extend(sorted(name for name in properties if name not in required))
        spec = Mql5StructSpec(
            name=struct_name,
            schema=schema,
            fields=[],
            comment=schema.get("$comment"),
            is_payload=is_payload,
        )
        self.structs[struct_name] = spec
        for field_name in names:
            field_schema = properties[field_name]
            field = self._field_spec(
                struct_name, field_name, field_schema, source_file, field_name in required
            )
            spec.fields.append(field)
        return struct_name

    def _field_spec(
        self,
        struct_name: str,
        field_name: str,
        schema: dict[str, Any],
        source_file: str,
        required: bool,
    ) -> Mql5FieldSpec:
        resolved = resolve_ref(schema, self.schemas, source_file)
        nullable = False
        if "oneOf" in resolved:
            non_null = [item for item in resolved["oneOf"] if item.get("type") != "null"]
            nullable = len(non_null) != len(resolved["oneOf"])
            if len(non_null) != 1 or not nullable:
                raise ValueError(f"unsupported oneOf for {struct_name}.{field_name}")
            resolved = resolve_ref(non_null[0], self.schemas, source_file)
        schema_type = resolved.get("type")
        if isinstance(schema_type, list):
            non_null_types = [item for item in schema_type if item != "null"]
            nullable = nullable or "null" in schema_type
            if len(non_null_types) != 1:
                raise ValueError(f"unsupported union for {struct_name}.{field_name}")
            resolved = {**resolved, "type": non_null_types[0]}
            schema_type = resolved["type"]
        if "const" in resolved:
            const_type = type(resolved["const"])
            if const_type is bool:
                schema_type = "boolean"
            elif const_type is int:
                schema_type = "integer"
            elif const_type is float:
                schema_type = "number"
            else:
                schema_type = "string"
        if "enum" in resolved:
            enum_name = self._enum_name(f"{struct_name.removeprefix('Farm')}_{field_name}")
            if enum_name not in self.enums:
                self.enums[enum_name] = [value for value in resolved["enum"] if value is not None]
            return Mql5FieldSpec(
                name=field_name,
                json_name=field_name,
                kind="enum",
                mql_type=enum_name,
                required=required,
                nullable=nullable,
                comment=resolved.get("description"),
            )
        if schema_type in ("string", "integer", "number", "boolean"):
            return Mql5FieldSpec(
                name=field_name,
                json_name=field_name,
                kind=str(schema_type),
                mql_type=self._mql_scalar_type(str(schema_type)),
                required=required,
                nullable=nullable,
                comment=resolved.get("description"),
            )
        if schema_type == "object":
            properties = resolved.get("properties", {})
            additional = resolved.get("additionalProperties")
            if properties:
                child_name = f"{struct_name}{PythonGenerator._class_name(field_name)}"
                self._add_struct(child_name, resolved, source_file, False)
                return Mql5FieldSpec(
                    name=field_name,
                    json_name=field_name,
                    kind="object",
                    mql_type=child_name,
                    required=required,
                    nullable=nullable,
                    comment=resolved.get("description"),
                )
            if isinstance(additional, dict):
                value_kind, value_type = self._map_value_type(
                    struct_name, field_name, additional, source_file
                )
                return Mql5FieldSpec(
                    name=field_name,
                    json_name=field_name,
                    kind="map",
                    mql_type="",
                    required=required,
                    nullable=nullable,
                    comment=resolved.get("description"),
                    value_kind=value_kind,
                    value_type=value_type,
                )
            if additional is True:
                return Mql5FieldSpec(
                    name=field_name,
                    json_name=field_name,
                    kind="map",
                    mql_type="",
                    required=required,
                    nullable=nullable,
                    comment=resolved.get("description"),
                    value_kind="raw",
                    value_type="string",
                )
        if schema_type == "array":
            item_schema = resolve_ref(resolved.get("items", {}), self.schemas, source_file)
            item_nullable = False
            item_type_raw = item_schema.get("type")
            if isinstance(item_type_raw, list):
                non_null = [item for item in item_type_raw if item != "null"]
                item_nullable = "null" in item_type_raw
                if len(non_null) != 1:
                    raise ValueError(f"unsupported array union for {struct_name}.{field_name}")
                item_schema = {**item_schema, "type": non_null[0]}
                item_type_raw = item_schema["type"]
            if item_nullable:
                raise ValueError(f"nullable array items are unsupported for {struct_name}.{field_name}")
            if "enum" in item_schema:
                enum_name = self._enum_name(f"{struct_name.removeprefix('Farm')}_{field_name}_item")
                if enum_name not in self.enums:
                    self.enums[enum_name] = [value for value in item_schema["enum"] if value is not None]
                return Mql5FieldSpec(
                    name=field_name,
                    json_name=field_name,
                    kind="array",
                    mql_type=enum_name,
                    required=required,
                    nullable=nullable,
                    comment=resolved.get("description"),
                    item_kind="enum",
                    item_type=enum_name,
                )
            if item_type_raw == "object" and item_schema.get("properties"):
                child_name = f"{struct_name}{PythonGenerator._class_name(field_name)}Item"
                self._add_struct(child_name, item_schema, source_file, False)
                return Mql5FieldSpec(
                    name=field_name,
                    json_name=field_name,
                    kind="array",
                    mql_type=child_name,
                    required=required,
                    nullable=nullable,
                    comment=resolved.get("description"),
                    item_kind="object",
                    item_type=child_name,
                )
            return Mql5FieldSpec(
                name=field_name,
                json_name=field_name,
                kind="array",
                mql_type=self._mql_scalar_type(str(item_type_raw)),
                required=required,
                nullable=nullable,
                comment=resolved.get("description"),
                item_kind=str(item_type_raw),
                item_type=self._mql_scalar_type(str(item_type_raw)),
            )
        raise ValueError(f"unsupported MQL5 schema for {struct_name}.{field_name}: {resolved}")

    def _map_value_type(
        self, struct_name: str, field_name: str, schema: dict[str, Any], source_file: str
    ) -> tuple[str, str]:
        resolved = resolve_ref(schema, self.schemas, source_file)
        if "enum" in resolved:
            enum_name = self._enum_name(f"{struct_name.removeprefix('Farm')}_{field_name}_value")
            if enum_name not in self.enums:
                self.enums[enum_name] = [value for value in resolved["enum"] if value is not None]
            return "enum", enum_name
        schema_type = resolved.get("type")
        if isinstance(schema_type, list):
            non_null = [item for item in schema_type if item != "null"]
            if len(non_null) != 1:
                raise ValueError(f"unsupported map union for {struct_name}.{field_name}")
            schema_type = non_null[0]
        return str(schema_type), self._mql_scalar_type(str(schema_type))

    def _emit_enums(self) -> list[str]:
        lines: list[str] = []
        for enum_name, values in self.enums.items():
            lines.extend([f"enum {enum_name}", "{"])
            for value in values:
                lines.append(f"   {self._enum_member(enum_name, str(value))},")
            lines.append(f"   {enum_name}_UNRECOGNIZED")
            lines.extend(["};", ""])
            lines.extend([f"string {self._enum_func_prefix(enum_name)}ToString(const {enum_name} v)", "{", "   switch(v)", "   {"])
            for value in values:
                lines.append(f"      case {self._enum_member(enum_name, str(value))}: return {mql_quote(str(value))};")
            lines.extend(["      default: return \"UNKNOWN\";", "   }", "}", ""])
            lines.extend([f"{enum_name} {self._enum_func_prefix(enum_name)}FromString(const string s, bool &ok)", "{", "   ok = true;"])
            for value in values:
                lines.append(f"   if(s == {mql_quote(str(value))}) return {self._enum_member(enum_name, str(value))};")
            lines.extend(["   ok = false;", f"   return {enum_name}_UNRECOGNIZED;", "}", ""])
        return lines

    def _emit_structs(self) -> list[str]:
        lines: list[str] = []
        ordered_specs = sorted(self.structs.values(), key=lambda item: item.name, reverse=True)
        for spec in ordered_specs:
            if spec.comment:
                for line in spec.comment.splitlines():
                    lines.append(f"// {line}")
            lines.extend([f"struct {spec.name}", "{"])
            if spec.is_payload:
                lines.append("   string raw_json;")
            for field in spec.fields:
                if field.comment:
                    for line in field.comment.splitlines():
                        lines.append(f"   // {line}")
                if not field.required:
                    lines.append(f"   bool   {field.name}_present;")
                if field.nullable:
                    lines.append(f"   bool   {field.name}_is_null;")
                if field.kind == "map":
                    lines.append(f"   string {field.name}_keys[];")
                    lines.append(f"   {self._align_type(field.value_type or 'string')} {field.name}_values[];")
                elif field.kind == "array":
                    lines.append(f"   {self._align_type(field.item_type or field.mql_type)} {field.name}[];")
                else:
                    lines.append(f"   {self._align_type(field.mql_type)} {field.name};")
            lines.extend(["", "   void Free()", "   {"])
            if spec.is_payload:
                lines.append("      raw_json = \"\";")
            for field in spec.fields:
                if not field.required:
                    lines.append(f"      {field.name}_present = false;")
                if field.nullable:
                    lines.append(f"      {field.name}_is_null = false;")
                if field.kind == "map":
                    lines.append(f"      ArrayResize({field.name}_keys, 0);")
                    lines.append(f"      ArrayResize({field.name}_values, 0);")
                elif field.kind == "array":
                    if field.item_kind == "object":
                        lines.append(f"      for(int i = 0; i < ArraySize({field.name}); i++) {field.name}[i].Free();")
                    lines.append(f"      ArrayResize({field.name}, 0);")
                elif field.kind == "object":
                    lines.append(f"      {field.name}.Free();")
            lines.extend(["   }", "};", ""])
        return lines

    def _emit_fill_helpers(self) -> list[str]:
        lines: list[str] = []
        ordered_specs = sorted(self.structs.values(), key=lambda item: item.name, reverse=True)
        for spec in ordered_specs:
            lines.extend([f"void FarmFill{spec.name.removeprefix('Farm')}(CFarmJsonValue *root, {spec.name} &out)", "{", "   out.Free();"])
            if spec.is_payload:
                canonical = spec.name.removeprefix("Farm").removesuffix("Payload")
                lines.append(f"   out.raw_json = FarmCanonical{canonical}(root);")
            for field in spec.fields:
                var = f"v_{field.name}"
                lines.append(f"   CFarmJsonValue *{var} = (root != NULL ? root.Get({mql_quote(field.json_name)}) : NULL);")
                if not field.required:
                    lines.append(f"   out.{field.name}_present = ({var} != NULL);")
                    lines.append(f"   if({var} == NULL) {{ }}")
                    lines.append("   else")
                    lines.append("   {")
                    inner_indent = "      "
                else:
                    inner_indent = "   "
                if field.nullable:
                    lines.append(f"{inner_indent}out.{field.name}_is_null = ({var} != NULL && {var}.type == FARM_JSON_NULL);")
                    lines.append(f"{inner_indent}if(out.{field.name}_is_null) {{ }}")
                    lines.append(f"{inner_indent}else")
                    lines.append(f"{inner_indent}{{")
                    inner_indent += "   "
                self._emit_fill_field(lines, field, var, inner_indent)
                if field.nullable:
                    inner_indent = inner_indent[:-3]
                    lines.append(f"{inner_indent}}}")
                if not field.required:
                    lines.append("   }")
            lines.extend(["}", ""])
        return lines

    def _emit_render_helpers(self) -> list[str]:
        lines: list[str] = []
        ordered_specs = sorted(self.structs.values(), key=lambda item: item.name, reverse=True)
        for spec in ordered_specs:
            lines.extend([f"string FarmRender{spec.name.removeprefix('Farm')}(const {spec.name} &src)", "{"])
            lines.append('   string out = "{";')
            lines.append("   bool first = true;")
            for field in spec.fields:
                if not field.required:
                    lines.append(f"   if(src.{field.name}_present)")
                    lines.append("   {")
                    indent = "      "
                else:
                    indent = "   "
                lines.append(f"{indent}FarmJsonAppendFieldPrefix(out, first, {mql_quote(field.json_name)});")
                if field.nullable:
                    lines.append(f"{indent}if(src.{field.name}_is_null)")
                    lines.append(f'{indent}   out += "null";')
                    lines.append(f"{indent}else")
                    lines.append(f"{indent}{{")
                    self._emit_render_field(lines, field, indent + "   ")
                    lines.append(f"{indent}}}")
                else:
                    self._emit_render_field(lines, field, indent)
                if not field.required:
                    lines.append("   }")
            lines.append('   out += "}";')
            lines.append("   return out;")
            lines.extend(["}", ""])
        return lines

    def _emit_render_field(
        self, lines: list[str], field: Mql5FieldSpec, indent: str
    ) -> None:
        if field.kind == "string":
            lines.append(f"{indent}out += FarmJsonQuoteUtf8(src.{field.name});")
        elif field.kind == "integer":
            lines.append(f"{indent}out += IntegerToString(src.{field.name});")
        elif field.kind == "number":
            lines.append(f"{indent}out += FarmJsonFormatDouble(src.{field.name});")
        elif field.kind == "boolean":
            lines.append(f'{indent}out += (src.{field.name} ? "true" : "false");')
        elif field.kind == "enum":
            lines.append(
                f"{indent}out += FarmJsonQuoteUtf8({self._enum_func_prefix(field.mql_type)}ToString(src.{field.name}));"
            )
        elif field.kind == "object":
            lines.append(f"{indent}out += FarmRender{field.mql_type.removeprefix('Farm')}(src.{field.name});")
        elif field.kind == "array":
            lines.append(f'{indent}out += "[";')
            lines.append(f"{indent}for(int i = 0; i < ArraySize(src.{field.name}); i++)")
            lines.append(f"{indent}{{")
            lines.append(f'{indent}   if(i > 0) out += ",";')
            self._emit_render_array_item(lines, field, indent + "   ")
            lines.append(f"{indent}}}")
            lines.append(f'{indent}out += "]";')
        elif field.kind == "map":
            lines.append(f'{indent}out += "{{";')
            lines.append(f"{indent}for(int i = 0; i < ArraySize(src.{field.name}_keys); i++)")
            lines.append(f"{indent}{{")
            lines.append(f'{indent}   if(i > 0) out += ",";')
            lines.append(f"{indent}   out += FarmJsonQuoteUtf8(src.{field.name}_keys[i]) + \":\";")
            self._emit_render_value(
                lines,
                f"src.{field.name}_values[i]",
                field.value_kind or "string",
                field.value_type or "string",
                indent + "   ",
            )
            lines.append(f"{indent}}}")
            lines.append(f'{indent}out += "}}";')

    def _emit_render_array_item(
        self, lines: list[str], field: Mql5FieldSpec, indent: str
    ) -> None:
        if field.item_kind == "object":
            lines.append(f"{indent}out += FarmRender{(field.item_type or '').removeprefix('Farm')}(src.{field.name}[i]);")
            return
        self._emit_render_value(
            lines,
            f"src.{field.name}[i]",
            field.item_kind or "string",
            field.item_type or "string",
            indent,
        )

    def _emit_render_value(
        self,
        lines: list[str],
        expr: str,
        kind: str,
        mql_type: str,
        indent: str,
    ) -> None:
        if kind == "string":
            lines.append(f"{indent}out += FarmJsonQuoteUtf8({expr});")
        elif kind == "integer":
            lines.append(f"{indent}out += IntegerToString({expr});")
        elif kind == "number":
            lines.append(f"{indent}out += FarmJsonFormatDouble({expr});")
        elif kind == "boolean":
            lines.append(f'{indent}out += ({expr} ? "true" : "false");')
        elif kind == "enum":
            lines.append(
                f"{indent}out += FarmJsonQuoteUtf8({self._enum_func_prefix(mql_type)}ToString({expr}));"
            )
        elif kind == "raw":
            lines.append(f"{indent}out += {expr};")

    def _emit_fill_field(
        self, lines: list[str], field: Mql5FieldSpec, value_var: str, indent: str
    ) -> None:
        if field.kind == "string":
            lines.append(f"{indent}out.{field.name} = ({value_var} != NULL && {value_var}.type == FARM_JSON_STRING ? {value_var}.string_value : \"\");")
        elif field.kind == "integer":
            lines.append(f"{indent}out.{field.name} = ({value_var} != NULL && {value_var}.type == FARM_JSON_NUMBER ? {value_var}.integer_value : 0);")
        elif field.kind == "number":
            lines.append(f"{indent}out.{field.name} = ({value_var} != NULL && {value_var}.type == FARM_JSON_NUMBER ? {value_var}.number_value : 0.0);")
        elif field.kind == "boolean":
            lines.append(f"{indent}out.{field.name} = ({value_var} != NULL && {value_var}.type == FARM_JSON_BOOL && {value_var}.bool_value);")
        elif field.kind == "enum":
            ok_name = f"ok_{field.name}"
            lines.append(f"{indent}bool {ok_name} = false;")
            lines.append(f"{indent}out.{field.name} = {self._enum_func_prefix(field.mql_type)}FromString(({value_var} != NULL && {value_var}.type == FARM_JSON_STRING ? {value_var}.string_value : \"\"), {ok_name});")
        elif field.kind == "object":
            lines.append(f"{indent}FarmFill{field.mql_type.removeprefix('Farm')}({value_var}, out.{field.name});")
        elif field.kind == "array":
            lines.append(f"{indent}const int n_{field.name} = ({value_var} != NULL && {value_var}.type == FARM_JSON_ARRAY ? {value_var}.Size() : 0);")
            lines.append(f"{indent}ArrayResize(out.{field.name}, n_{field.name});")
            lines.append(f"{indent}for(int i = 0; i < n_{field.name}; i++)")
            lines.append(f"{indent}{{")
            lines.append(f"{indent}   CFarmJsonValue *item = {value_var}.At(i);")
            self._emit_fill_array_item(lines, field, "item", indent + "   ")
            lines.append(f"{indent}}}")
        elif field.kind == "map":
            lines.append(f"{indent}const int n_{field.name} = ({value_var} != NULL && {value_var}.type == FARM_JSON_OBJECT ? {value_var}.Size() : 0);")
            lines.append(f"{indent}ArrayResize(out.{field.name}_keys, n_{field.name});")
            lines.append(f"{indent}ArrayResize(out.{field.name}_values, n_{field.name});")
            lines.append(f"{indent}for(int i = 0; i < n_{field.name}; i++)")
            lines.append(f"{indent}{{")
            lines.append(f"{indent}   out.{field.name}_keys[i] = {value_var}.KeyAt(i);")
            lines.append(f"{indent}   CFarmJsonValue *item = {value_var}.At(i);")
            self._emit_fill_value_assignment(
                lines,
                f"out.{field.name}_values[i]",
                field.value_kind or "string",
                field.value_type or "string",
                "item",
                indent + "   ",
            )
            lines.append(f"{indent}}}")

    def _emit_fill_array_item(
        self, lines: list[str], field: Mql5FieldSpec, value_var: str, indent: str
    ) -> None:
        if field.item_kind == "object":
            lines.append(f"{indent}FarmFill{(field.item_type or '').removeprefix('Farm')}({value_var}, out.{field.name}[i]);")
            return
        self._emit_fill_value_assignment(
            lines,
            f"out.{field.name}[i]",
            field.item_kind or "string",
            field.item_type or "string",
            value_var,
            indent,
        )

    def _emit_fill_value_assignment(
        self,
        lines: list[str],
        target: str,
        kind: str,
        mql_type: str,
        value_var: str,
        indent: str,
    ) -> None:
        if kind == "string":
            lines.append(f"{indent}{target} = ({value_var} != NULL && {value_var}.type == FARM_JSON_STRING ? {value_var}.string_value : \"\");")
        elif kind == "integer":
            lines.append(f"{indent}{target} = ({value_var} != NULL && {value_var}.type == FARM_JSON_NUMBER ? {value_var}.integer_value : 0);")
        elif kind == "number":
            lines.append(f"{indent}{target} = ({value_var} != NULL && {value_var}.type == FARM_JSON_NUMBER ? {value_var}.number_value : 0.0);")
        elif kind == "boolean":
            lines.append(f"{indent}{target} = ({value_var} != NULL && {value_var}.type == FARM_JSON_BOOL && {value_var}.bool_value);")
        elif kind == "enum":
            lines.append(f"{indent}bool ok = false;")
            lines.append(f"{indent}{target} = {self._enum_func_prefix(mql_type)}FromString(({value_var} != NULL && {value_var}.type == FARM_JSON_STRING ? {value_var}.string_value : \"\"), ok);")
        elif kind == "raw":
            lines.append(f"{indent}{target} = ({value_var} != NULL ? {value_var}.ToJson() : \"null\");")

    @staticmethod
    def _mql_scalar_type(schema_type: str) -> str:
        if schema_type == "integer":
            return "long"
        if schema_type == "number":
            return "double"
        if schema_type == "boolean":
            return "bool"
        return "string"

    @staticmethod
    def _align_type(mql_type: str) -> str:
        return mql_type

    @staticmethod
    def _enum_name(raw: str) -> str:
        value = re.sub(r"[^A-Za-z0-9]+", "_", raw).upper().strip("_")
        return "ENUM_FARM_" + value

    @staticmethod
    def _enum_member(enum_name: str, value: str) -> str:
        member = re.sub(r"[^A-Za-z0-9]+", "_", value).upper().strip("_")
        if not member or member[0].isdigit():
            member = "V_" + member
        return enum_name.removeprefix("ENUM_") + "_" + member

    @staticmethod
    def _enum_func_prefix(enum_name: str) -> str:
        return "".join(part.capitalize() for part in enum_name.removeprefix("ENUM_").lower().split("_"))

    def _helpers(self, msg_types: list[str]) -> list[str]:
        lines: list[str] = [
            "string FarmMsgTypeToString(const ENUM_FARM_MSG_TYPE v)",
            "{",
            "   switch(v)",
            "   {",
        ]
        for msg_type in msg_types:
            lines.append(f"      case FARM_MSG_{msg_type}: return \"{msg_type}\";")
        lines.extend(
            [
                "      default: return \"UNKNOWN\";",
                "   }",
                "}",
                "",
                "ENUM_FARM_MSG_TYPE FarmMsgTypeFromString(const string s)",
                "{",
            ]
        )
        for msg_type in msg_types:
            lines.append(f"   if(s == \"{msg_type}\") return FARM_MSG_{msg_type};")
        lines.extend(
            [
                "   return FARM_MSG_UNKNOWN;",
                "}",
                "",
                "bool FarmLooksLikeUlid(const string s)",
                "{",
                "   if(StringLen(s) != 26) return false;",
                "   const string alphabet = \"0123456789ABCDEFGHJKMNPQRSTVWXYZ\";",
                "   for(int i = 0; i < StringLen(s); i++)",
                "   {",
                "      if(StringFind(alphabet, ShortToString(StringGetCharacter(s, i))) < 0)",
                "         return false;",
                "   }",
                "   return true;",
                "}",
                "",
                "bool FarmLooksLikeSymbol(const string s)",
                "{",
                "   if(StringLen(s) < 3 || StringLen(s) > 24) return false;",
                "   int dot_count = 0;",
                "   int dot_pos = -1;",
                "   for(int i = 0; i < StringLen(s); i++)",
                "   {",
                "      const ushort ch = StringGetCharacter(s, i);",
                "      const bool upper_digit = (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9');",  # noqa: E501
                "      const bool suffix = (ch >= 'a' && ch <= 'z') || upper_digit;",
                "      if(ch == '.') { dot_count++; dot_pos = i; continue; }",
                "      if(dot_count == 0 && !upper_digit) return false;",
                "      if(dot_count > 0 && !suffix) return false;",
                "   }",
                "   if(dot_count > 1) return false;",
                "   if(dot_count == 1 && (dot_pos < 3 || StringLen(s) - dot_pos - 1 < 1 || StringLen(s) - dot_pos - 1 > 8)) return false;",  # noqa: E501
                "   if(dot_count == 0 && StringLen(s) > 15) return false;",
                "   return true;",
                "}",
                "",
                "bool FarmLooksLikeTsUtc(const string s)",
                "{",
                "   const int n = StringLen(s);",
                "   if(n != 20 && n < 22) return false;",
                "   if(StringGetCharacter(s, n - 1) != 'Z') return false;",
                "   if(StringFind(s, \"+\") >= 0) return false;",
                "   if(StringGetCharacter(s, 4) != '-' || StringGetCharacter(s, 7) != '-' || StringGetCharacter(s, 10) != 'T') return false;",  # noqa: E501
                "   if(StringGetCharacter(s, 13) != ':' || StringGetCharacter(s, 16) != ':') return false;",  # noqa: E501
                "   if(n == 20) return true;",
                "   if(StringGetCharacter(s, 19) != '.') return false;",
                "   const int frac = n - 21;",
                "   return frac >= 1 && frac <= 3;",
                "}",
                "",
                "bool FarmRequireObjectKey(CFarmJsonValue *obj, const string key)",
                "{",
                "   if(obj == NULL || obj.type != FARM_JSON_OBJECT || !obj.Has(key))",
                "   {",
                "      FarmJsonSetError(\"MISSING_REQUIRED\", key);",
                "      return false;",
                "   }",
                "   return true;",
                "}",
                "",
                "bool FarmRequireKeys(CFarmJsonValue *obj, const string &keys[])",
                "{",
                "   string missing = \"\";",
                "   for(int i = 0; i < ArraySize(keys); i++)",
                "   {",
                "      if(obj == NULL || obj.type != FARM_JSON_OBJECT || !obj.Has(keys[i]))",
                "      {",
                "         if(missing != \"\") missing += \",\";",
                "         missing += keys[i];",
                "      }",
                "   }",
                "   if(missing != \"\")",
                "   {",
                "      FarmJsonSetError(\"MISSING_REQUIRED\", missing);",
                "      return false;",
                "   }",
                "   return true;",
                "}",
                "",
                "bool FarmValidateEnvelopeDoc(CFarmJsonValue *root, FarmEnvelope &out)",
                "{",
                "   if(root == NULL || root.type != FARM_JSON_OBJECT) { FarmJsonSetError(\"EXPECTED_OBJECT\", \"envelope\"); return false; }",  # noqa: E501
                "   string required[] = {\"v\",\"type\",\"msg_id\",\"session_id\",\"ts_server\",\"ts_sent\",\"payload\"};",  # noqa: E501
                "   if(!FarmRequireKeys(root, required)) return false;",
                "   CFarmJsonValue *v = root.Get(\"v\");",
                "   CFarmJsonValue *type = root.Get(\"type\");",
                "   CFarmJsonValue *msg_id = root.Get(\"msg_id\");",
                "   CFarmJsonValue *session_id = root.Get(\"session_id\");",
                "   CFarmJsonValue *ts_server = root.Get(\"ts_server\");",
                "   CFarmJsonValue *ts_sent = root.Get(\"ts_sent\");",
                "   CFarmJsonValue *payload = root.Get(\"payload\");",
                "   if(v.type != FARM_JSON_NUMBER || v.integer_value != 1) { FarmJsonSetError(\"BAD_FIELD\", \"v\"); return false; }",  # noqa: E501
                "   if(type.type != FARM_JSON_STRING) { FarmJsonSetError(\"BAD_FIELD\", \"type\"); return false; }",  # noqa: E501
                "   if(msg_id.type != FARM_JSON_STRING || !FarmLooksLikeUlid(msg_id.string_value)) { FarmJsonSetError(\"BAD_FIELD\", \"msg_id\"); return false; }",  # noqa: E501
                "   if(session_id.type != FARM_JSON_STRING || StringFind(session_id.string_value, \"PERIOD_\") >= 0) { FarmJsonSetError(\"BAD_FIELD\", \"session_id\"); return false; }",  # noqa: E501
                "   if(ts_server.type != FARM_JSON_STRING || !FarmLooksLikeTsUtc(ts_server.string_value)) { FarmJsonSetError(\"BAD_FIELD\", \"ts_server\"); return false; }",  # noqa: E501
                "   if(ts_sent.type != FARM_JSON_STRING || !FarmLooksLikeTsUtc(ts_sent.string_value)) { FarmJsonSetError(\"BAD_FIELD\", \"ts_sent\"); return false; }",  # noqa: E501
                "   if(payload.type != FARM_JSON_OBJECT) { FarmJsonSetError(\"BAD_FIELD\", \"payload\"); return false; }",  # noqa: E501
                "   out.v = 1;",
                "   out.type_raw = type.string_value;",
                "   out.type = FarmMsgTypeFromString(out.type_raw);",
                "   out.msg_id = msg_id.string_value;",
                "   out.session_id = session_id.string_value;",
                "   out.ts_server = ts_server.string_value;",
                "   out.ts_sent = ts_sent.string_value;",
                "   out.payload_json = payload.ToJson();",
                "   return true;",
                "}",
                "",
                "bool FarmParseEnvelope(const string line, FarmEnvelope &out)",
                "{",
                "   CFarmJsonDoc doc;",
                "   if(!doc.Parse(line)) return false;",
                "   const bool ok = FarmValidateEnvelopeDoc(doc.Root(), out);",
                "   doc.Free();",
                "   return ok;",
                "}",
                "",
                "bool FarmSerializeEnvelope(const FarmEnvelope &src, string &out_line)",
                "{",
                "   const string type = (src.type == FARM_MSG_UNKNOWN ? src.type_raw : FarmMsgTypeToString(src.type));",  # noqa: E501
                "   out_line = \"{\"",
                "      + \"\\\"v\\\":\" + IntegerToString(src.v)",
                "      + \",\\\"type\\\":\" + FarmJsonQuoteUtf8(type)",
                "      + \",\\\"msg_id\\\":\" + FarmJsonQuoteUtf8(src.msg_id)",
                "      + \",\\\"session_id\\\":\" + FarmJsonQuoteUtf8(src.session_id)",
                "      + \",\\\"ts_server\\\":\" + FarmJsonQuoteUtf8(src.ts_server)",
                "      + \",\\\"ts_sent\\\":\" + FarmJsonQuoteUtf8(src.ts_sent)",
                "      + \",\\\"payload\\\":\" + src.payload_json + \"}\";",
                "   return true;",
                "}",
                "",
                "bool FarmValidateState(CFarmJsonValue *payload)",
                "{",
                "   string required[] = {\"balance\",\"equity\",\"margin_used\",\"margin_free\",\"margin_level_pct\",\"equity_hwm\",\"day_start_equity\",\"day_pl\",\"day_pl_pct\",\"positions\",\"pending_orders\",\"owned_net\",\"owned_ticket_count\",\"foreign_positions\",\"account_margin_mode\",\"guard\"};",  # noqa: E501
                "   if(!FarmRequireKeys(payload, required)) return false;",
                "   CFarmJsonValue *positions = payload.Get(\"positions\");",
                "   if(positions.type != FARM_JSON_ARRAY) { FarmJsonSetError(\"BAD_FIELD\", \"positions\"); return false; }",  # noqa: E501
                "   for(int i = 0; i < positions.Size(); i++)",
                "   {",
                "      CFarmJsonValue *pos = positions.At(i);",
                "      if(pos == NULL || pos.type != FARM_JSON_OBJECT) { FarmJsonSetError(\"BAD_FIELD\", \"positions[]\"); return false; }",  # noqa: E501
                "      string pos_required[] = {\"ticket\",\"symbol\",\"side\",\"volume\",\"price_open\",\"sl\",\"tp\",\"profit\",\"swap\",\"magic\",\"time_open\"};",  # noqa: E501
                "      if(!FarmRequireKeys(pos, pos_required)) return false;",
                "      CFarmJsonValue *sl = pos.Get(\"sl\");",
                "      if(sl.type == FARM_JSON_NUMBER && sl.number_value <= 0.0) { FarmJsonSetError(\"BAD_FIELD\", \"sl\"); return false; }",  # noqa: E501
                "      CFarmJsonValue *comment = pos.Get(\"comment\");",
                "      if(comment != NULL && comment.type != FARM_JSON_NULL && comment.type != FARM_JSON_STRING) { FarmJsonSetError(\"BAD_FIELD\", \"comment\"); return false; }",  # noqa: E501
                "   }",
                "   CFarmJsonValue *owned_net = payload.Get(\"owned_net\");",
                "   if(owned_net.type != FARM_JSON_OBJECT) { FarmJsonSetError(\"BAD_FIELD\", \"owned_net\"); return false; }",  # noqa: E501
                "   for(int i = 0; i < owned_net.Size(); i++)",
                "   {",
                "      if(!FarmLooksLikeSymbol(owned_net.KeyAt(i))) { FarmJsonSetError(\"BAD_FIELD\", \"owned_net\"); return false; }",  # noqa: E501
                "   }",
                "   return true;",
                "}",
                "",
                "bool FarmValidatePayload(const ENUM_FARM_MSG_TYPE msg_type, CFarmJsonValue *payload)",  # noqa: E501
                "{",
                "   if(payload == NULL || payload.type != FARM_JSON_OBJECT) { FarmJsonSetError(\"EXPECTED_OBJECT\", \"payload\"); return false; }",  # noqa: E501
                "   if(msg_type == FARM_MSG_UNKNOWN) return true;",
                "   if(msg_type == FARM_MSG_BAR)",
                "   {",
                "      if(!FarmRequireObjectKey(payload, \"is_final\")) return false;",
                "      CFarmJsonValue *is_final = payload.Get(\"is_final\");",
                "      if(is_final.type != FARM_JSON_BOOL || !is_final.bool_value) { FarmJsonSetError(\"BAD_FIELD\", \"is_final\"); return false; }",  # noqa: E501
                "   }",
                "   if(msg_type == FARM_MSG_HELLO)",
                "   {",
                "      if(!FarmRequireObjectKey(payload, \"token\")) return false;",
                "      CFarmJsonValue *account = payload.Get(\"account\");",
                "      if(account != NULL && account.type == FARM_JSON_OBJECT)",
                "      {",
                "         CFarmJsonValue *mode = account.Get(\"margin_mode\");",
                "         if(mode != NULL && mode.type == FARM_JSON_STRING && mode.string_value == \"retail_hedging\") { FarmJsonSetError(\"BAD_FIELD\", \"account.margin_mode\"); return false; }",  # noqa: E501
                "      }",
                "   }",
                "   if(msg_type == FARM_MSG_STATE && !FarmValidateState(payload)) return false;",
                "   if(msg_type == FARM_MSG_RISK_DIRECTIVE)",
                "   {",
                "      if(!FarmRequireObjectKey(payload, \"scale_factor\")) return false;",
                "      CFarmJsonValue *scale = payload.Get(\"scale_factor\");",
                "      if(scale.type != FARM_JSON_NUMBER || scale.number_value < 0.0 || scale.number_value > 1.0) { FarmJsonSetError(\"BAD_FIELD\", \"scale_factor\"); return false; }",  # noqa: E501
                "   }",
                "   if(msg_type == FARM_MSG_CONFIG_UPDATE)",
                "   {",
                "      CFarmJsonValue *settings = payload.Get(\"settings\");",
                "      if(settings == NULL || settings.type != FARM_JSON_OBJECT) { FarmJsonSetError(\"MISSING_REQUIRED\", \"settings\"); return false; }",  # noqa: E501
                "      for(int i = 0; i < settings.Size(); i++)",
                "      {",
                "         const string key = settings.KeyAt(i);",
                "         if(key != \"verbose_log\" && key != \"heartbeat_sec\" && key != \"state_interval_sec\" && key != \"bar_backfill_count\") { FarmJsonSetError(\"UNKNOWN_FIELD\", \"settings.\" + key); return false; }",  # noqa: E501
                "      }",
                "   }",
                "   return true;",
                "}",
                "",
            ]
        )
        lines.extend(self._canonical_payload_prototypes())
        lines.extend(self._canonical_payload_helpers())
        lines.extend(self._emit_fill_helpers())
        lines.extend(self._emit_render_helpers())
        payload_functions = {
            "Hello": "HELLO",
            "HelloAck": "HELLO_ACK",
            "Heartbeat": "HEARTBEAT",
            "HeartbeatAck": "HEARTBEAT_ACK",
            "Bar": "BAR",
            "State": "STATE",
            "Intent": "INTENT",
            "IntentAck": "INTENT_ACK",
            "ExecReport": "EXEC_REPORT",
            "RiskDirective": "RISK_DIRECTIVE",
            "ConfigUpdate": "CONFIG_UPDATE",
            "Error": "ERROR",
        }
        for name, msg_type in payload_functions.items():
            lines.extend(
                [
                    f"bool FarmParse{name}(const string json, Farm{name}Payload &out)",
                    "{",
                    "   CFarmJsonDoc doc;",
                    "   if(!doc.Parse(json)) return false;",
                    f"   if(!FarmValidatePayload(FARM_MSG_{msg_type}, doc.Root())) {{ doc.Free(); return false; }}",
                    f"   FarmFill{name}Payload(doc.Root(), out);",
                    "   doc.Free();",
                    "   return true;",
                    "}",
                    "",
                    f"bool FarmSerialize{name}(const Farm{name}Payload &src, string &out_json)",
                    "{",
                    f"   out_json = FarmRender{name}Payload(src);",
                    "   return true;",
                    "}",
                    "",
                ]
            )
        return lines

    def _canonical_payload_prototypes(self) -> list[str]:
        lines: list[str] = []
        for schema_name in PAYLOAD_FILES:
            function_name = f"FarmCanonical{PythonGenerator._class_name(schema_name)}"
            lines.append(f"string {function_name}(CFarmJsonValue *value);")
        lines.extend(
            [
                "string FarmCanonicalizePayloadJson(const ENUM_FARM_MSG_TYPE msg_type, CFarmJsonValue *payload);",  # noqa: E501
                "",
            ]
        )
        return lines

    def _canonical_payload_helpers(self) -> list[str]:
        lines: list[str] = []
        for schema_name in PAYLOAD_FILES:
            function_name = f"FarmCanonical{PythonGenerator._class_name(schema_name)}"
            schema_file = f"{schema_name}.json"
            lines.extend(
                [
                    f"string {function_name}(CFarmJsonValue *value)",
                    "{",
                ]
            )
            self._emit_canonical_value(
                lines,
                "value",
                self.schemas[schema_file],
                schema_file,
                "   ",
                "root",
            )
            lines.extend(["}", ""])
        lines.extend(
            [
                "string FarmCanonicalizePayloadJson(const ENUM_FARM_MSG_TYPE msg_type, CFarmJsonValue *payload)",  # noqa: E501
                "{",
            ]
        )
        for msg_type, payload_name in TYPE_TO_PAYLOAD.items():
            schema_name = payload_name.removesuffix("Payload")
            lines.append(f"   if(msg_type == FARM_MSG_{msg_type})")
            lines.append(f"      return FarmCanonical{schema_name}(payload);")
        lines.extend(
            [
                "   return FarmJsonCanonicalValue(payload);",
                "}",
                "",
            ]
        )
        return lines

    def _emit_canonical_value(
        self,
        lines: list[str],
        value_expr: str,
        schema: dict[str, Any],
        source_file: str,
        indent: str,
        prefix: str,
    ) -> None:
        schema = resolve_ref(schema, self.schemas, source_file)
        if "oneOf" in schema:
            non_null = [item for item in schema["oneOf"] if item.get("type") != "null"]
            lines.append(f"{indent}if({value_expr} != NULL && {value_expr}.type == FARM_JSON_NULL)")
            lines.append(f'{indent}   return "null";')
            self._emit_canonical_value(
                lines,
                value_expr,
                non_null[0] if non_null else {"type": "null"},
                source_file,
                indent,
                prefix,
            )
            return
        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            non_null = [item for item in schema_type if item != "null"]
            lines.append(f"{indent}if({value_expr} != NULL && {value_expr}.type == FARM_JSON_NULL)")
            lines.append(f'{indent}   return "null";')
            self._emit_canonical_value(
                lines,
                value_expr,
                {**schema, "type": non_null[0] if non_null else "null"},
                source_file,
                indent,
                prefix,
            )
            return
        if schema_type == "integer":
            lines.append(f"{indent}return FarmJsonCanonicalNumber({value_expr}, true);")
            return
        if schema_type == "number":
            lines.append(f"{indent}return FarmJsonCanonicalNumber({value_expr}, false);")
            return
        if schema_type == "array":
            item_schema = schema.get("items", {})
            lines.extend([f'{indent}string out = "[";', f"{indent}if({value_expr} != NULL)"])
            lines.append(f"{indent}{{")
            lines.append(f"{indent}   for(int i = 0; i < {value_expr}.Size(); i++)")
            lines.append(f"{indent}   {{")
            lines.append(f"{indent}      if(i > 0) out += \",\";")
            self._emit_append_canonical_value(
                lines,
                f"{value_expr}.At(i)",
                item_schema,
                source_file,
                indent + "      ",
                f"{prefix}_item",
            )
            lines.append(f"{indent}   }}")
            lines.append(f"{indent}}}")
            lines.append(f'{indent}return out + "]";')
            return
        if schema_type == "object":
            properties = schema.get("properties", {})
            additional = schema.get("additionalProperties")
            if not properties and isinstance(additional, dict):
                self._emit_dynamic_object(
                    lines,
                    value_expr,
                    additional,
                    source_file,
                    indent,
                    prefix,
                )
                return
            required = list(schema.get("required", []))
            names = [name for name in required if name in properties]
            names.extend(sorted(name for name in properties if name not in required))
            lines.extend([f'{indent}string out = "{{";', f"{indent}bool first = true;"])
            for index, name in enumerate(names):
                child = f"{prefix}_{index}"
                lines.append(f'{indent}CFarmJsonValue *{child} = {value_expr}.Get("{name}");')
                lines.append(f"{indent}if({child} != NULL)")
                lines.append(f"{indent}{{")
                lines.append(f'{indent}   FarmJsonAppendFieldPrefix(out, first, "{name}");')
                self._emit_append_canonical_value(
                    lines, child, properties[name], source_file, indent + "   ", child
                )
                lines.append(f"{indent}}}")
            lines.append(f'{indent}return out + "}}";')
            return
        lines.append(f"{indent}return FarmJsonCanonicalValue({value_expr});")

    def _emit_append_canonical_value(
        self,
        lines: list[str],
        value_expr: str,
        schema: dict[str, Any],
        source_file: str,
        indent: str,
        prefix: str,
    ) -> None:
        schema = resolve_ref(schema, self.schemas, source_file)
        if "oneOf" in schema:
            non_null = [item for item in schema["oneOf"] if item.get("type") != "null"]
            lines.append(f"{indent}if({value_expr} != NULL && {value_expr}.type == FARM_JSON_NULL)")
            lines.append(f'{indent}   out += "null";')
            lines.append(f"{indent}else")
            lines.append(f"{indent}{{")
            self._emit_append_canonical_value(
                lines,
                value_expr,
                non_null[0] if non_null else {"type": "null"},
                source_file,
                indent + "   ",
                prefix,
            )
            lines.append(f"{indent}}}")
            return
        schema_type = schema.get("type")
        if isinstance(schema_type, list):
            non_null = [item for item in schema_type if item != "null"]
            lines.append(f"{indent}if({value_expr} != NULL && {value_expr}.type == FARM_JSON_NULL)")
            lines.append(f'{indent}   out += "null";')
            lines.append(f"{indent}else")
            lines.append(f"{indent}{{")
            self._emit_append_canonical_value(
                lines,
                value_expr,
                {**schema, "type": non_null[0] if non_null else "null"},
                source_file,
                indent + "   ",
                prefix,
            )
            lines.append(f"{indent}}}")
            return
        if schema_type == "integer":
            lines.append(f"{indent}out += FarmJsonCanonicalNumber({value_expr}, true);")
            return
        if schema_type == "number":
            lines.append(f"{indent}out += FarmJsonCanonicalNumber({value_expr}, false);")
            return
        if schema_type == "array":
            item_schema = schema.get("items", {})
            lines.append(f'{indent}out += "[";')
            lines.append(f"{indent}if({value_expr} != NULL)")
            lines.append(f"{indent}{{")
            lines.append(f"{indent}   for(int i = 0; i < {value_expr}.Size(); i++)")
            lines.append(f"{indent}   {{")
            lines.append(f"{indent}      if(i > 0) out += \",\";")
            self._emit_append_canonical_value(
                lines,
                f"{value_expr}.At(i)",
                item_schema,
                source_file,
                indent + "      ",
                f"{prefix}_item",
            )
            lines.append(f"{indent}   }}")
            lines.append(f"{indent}}}")
            lines.append(f'{indent}out += "]";')
            return
        if schema_type == "object":
            properties = schema.get("properties", {})
            additional = schema.get("additionalProperties")
            if not properties and isinstance(additional, dict):
                self._emit_append_dynamic_object(
                    lines, value_expr, additional, source_file, indent, prefix
                )
                return
            required = list(schema.get("required", []))
            names = [name for name in required if name in properties]
            names.extend(sorted(name for name in properties if name not in required))
            lines.append(f'{indent}out += "{{";')
            lines.append(f"{indent}bool {prefix}_first = true;")
            for index, name in enumerate(names):
                child = f"{prefix}_{index}"
                lines.append(f'{indent}CFarmJsonValue *{child} = {value_expr}.Get("{name}");')
                lines.append(f"{indent}if({child} != NULL)")
                lines.append(f"{indent}{{")
                lines.append(
                    f'{indent}   FarmJsonAppendFieldPrefix(out, {prefix}_first, "{name}");'
                )
                self._emit_append_canonical_value(
                    lines, child, properties[name], source_file, indent + "   ", child
                )
                lines.append(f"{indent}}}")
            lines.append(f'{indent}out += "}}";')
            return
        lines.append(f"{indent}out += FarmJsonCanonicalValue({value_expr});")

    def _emit_dynamic_object(
        self,
        lines: list[str],
        value_expr: str,
        additional_schema: dict[str, Any],
        source_file: str,
        indent: str,
        prefix: str,
    ) -> None:
        lines.extend([f'{indent}string out = "{{";', f"{indent}if({value_expr} != NULL)"])
        lines.append(f"{indent}{{")
        lines.append(f"{indent}   for(int i = 0; i < {value_expr}.Size(); i++)")
        lines.append(f"{indent}   {{")
        lines.append(f"{indent}      if(i > 0) out += \",\";")
        lines.append(f"{indent}      out += FarmJsonQuoteUtf8({value_expr}.KeyAt(i)) + \":\";")
        self._emit_append_canonical_value(
            lines,
            f"{value_expr}.At(i)",
            additional_schema,
            source_file,
            indent + "      ",
            f"{prefix}_value",
        )
        lines.append(f"{indent}   }}")
        lines.append(f"{indent}}}")
        lines.append(f'{indent}return out + "}}";')

    def _emit_append_dynamic_object(
        self,
        lines: list[str],
        value_expr: str,
        additional_schema: dict[str, Any],
        source_file: str,
        indent: str,
        prefix: str,
    ) -> None:
        lines.append(f'{indent}out += "{{";')
        lines.append(f"{indent}if({value_expr} != NULL)")
        lines.append(f"{indent}{{")
        lines.append(f"{indent}   for(int i = 0; i < {value_expr}.Size(); i++)")
        lines.append(f"{indent}   {{")
        lines.append(f"{indent}      if(i > 0) out += \",\";")
        lines.append(f"{indent}      out += FarmJsonQuoteUtf8({value_expr}.KeyAt(i)) + \":\";")
        self._emit_append_canonical_value(
            lines,
            f"{value_expr}.At(i)",
            additional_schema,
            source_file,
            indent + "      ",
            f"{prefix}_value",
        )
        lines.append(f"{indent}   }}")
        lines.append(f"{indent}}}")
        lines.append(f'{indent}out += "}}";')


def load_schemas() -> dict[str, dict[str, Any]]:
    return {
        path.name: json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(SCHEMA_DIR.glob("*.json"))
    }


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", newline="\n", delete=False, dir=path.parent
    ) as fh:
        fh.write(content)
        tmp = Path(fh.name)
    tmp.replace(path)


def sample_for(
    schema: dict[str, Any],
    schemas: dict[str, dict[str, Any]],
    *,
    minimal: bool,
    source_file: str = "common.json",
) -> Any:
    schema = resolve_ref(schema, schemas, source_file)
    if "oneOf" in schema:
        non_null = [item for item in schema["oneOf"] if item.get("type") != "null"]
        return (
            sample_for(non_null[0], schemas, minimal=minimal, source_file=source_file)
            if non_null
            else None
        )
    if "const" in schema:
        return schema["const"]
    if "enum" in schema:
        return next(value for value in schema["enum"] if value is not None)
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        non_null = [item for item in schema_type if item != "null"]
        if "null" in schema_type and minimal:
            return None
        return sample_for(
            {**schema, "type": non_null[0]},
            schemas,
            minimal=minimal,
            source_file=source_file,
        )
    if schema_type == "string":
        pattern = schema.get("pattern", "")
        if pattern == "^[0-9A-HJKMNP-TV-Z]{26}$":
            return ULID
        if pattern.startswith("^acct-"):
            return SESSION_ID
        if pattern.startswith("^[A-Z0-9]{3,15}"):
            return SYMBOL
        if pattern == "^[A-Z]{3}$":
            return "USD"
        if pattern == "^[0-9]+\\.[0-9]+\\.[0-9]+$":
            return "1.0.0"
        if pattern == "^[A-Z][A-Z0-9_]{2,63}$":
            return "BAD_REQUEST"
        if pattern.startswith("^[a-z0-9_]"):
            return "trend_v1"
        if pattern.startswith("^sha256:"):
            return "sha256:abcdef12"
        if "Z$" in pattern:
            return TS
        return "value"
    if schema_type == "integer":
        return max(1, int(schema.get("minimum", 1)))
    if schema_type == "number":
        minimum = schema.get("exclusiveMinimum", schema.get("minimum", 1.0))
        if minimum == 0:
            return 1.0
        if minimum < 0:
            return 0.0
        return float(minimum)
    if schema_type == "boolean":
        return True
    if schema_type == "array":
        if minimal:
            return []
        return [sample_for(schema["items"], schemas, minimal=minimal, source_file=source_file)]
    if schema_type == "object":
        props = schema.get("properties", {})
        required = list(schema.get("required", []))
        names = (
            required
            if minimal
            else [*required, *sorted(name for name in props if name not in required)]
        )
        if props:
            return {
                name: sample_for(props[name], schemas, minimal=minimal, source_file=source_file)
                for name in names
                if name in props
            }
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return {
                SYMBOL: sample_for(additional, schemas, minimal=minimal, source_file=source_file)
            }
        return {}
    raise ValueError(f"cannot make sample for schema: {schema}")


def resolve_ref(
    schema: dict[str, Any], schemas: dict[str, dict[str, Any]], source_file: str
) -> dict[str, Any]:
    if "$ref" not in schema:
        return schema
    filename, _, pointer = schema["$ref"].partition("#/")
    if not filename:
        filename = source_file
    target: Any = schemas[filename]
    for part in pointer.split("/"):
        target = target[part]
    merged = dict(target)
    for key, value in schema.items():
        if key != "$ref":
            merged[key] = value
    return merged


def envelope_for(msg_type: str, payload: dict[str, Any]) -> dict[str, Any]:
    return OrderedDict(
        [
            ("v", 1),
            ("type", msg_type),
            ("msg_id", ULID),
            ("session_id", SESSION_ID),
            ("ts_server", TS),
            ("ts_sent", TS_MS),
            ("payload", payload),
        ]
    )


def dumps_json(data: Any) -> str:
    return dumps_canonical_json(data, trailing_newline=True)


def write_python_models(schemas: dict[str, dict[str, Any]]) -> None:
    generator = PythonGenerator(schemas)
    content = generator.generate()
    atomic_write(PY_OUT_DIR / "models.py", content)
    symbols = [*generator.public_symbols(), *SYMBOLS_PUBLIC]
    init = "\n".join(
        [
            "# GENERATED by tools/codegen.py from contracts/schema/ -- DO NOT EDIT",
            "# Edit schema and rerun `python tools/task.py codegen`.",
            "",
            "from .models import (",
            *[f"    {symbol}," for symbol in generator.public_symbols()],
            ")",
            "from .symbols import (",
            *[f"    {symbol}," for symbol in SYMBOLS_PUBLIC],
            ")",
            "",
            "__all__ = [",
            *[f"    {symbol!r}," for symbol in symbols],
            "]",
            "",
        ]
    )
    atomic_write(PY_OUT_DIR / "__init__.py", init)


def write_mql5_models(schemas: dict[str, dict[str, Any]]) -> None:
    content = Mql5Generator(schemas).generate()
    atomic_write(MQL5_OUT_DIR / "FarmMessages.mqh", content)


def mql_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def write_python_symbols(data: dict[str, Any]) -> None:
    validate_symbol_registry_data(data)
    brokers = {
        broker: dict(sorted(mapping.items()))
        for broker, mapping in sorted(data["brokers"].items())
    }
    canonicals = {
        canonical: dict(sorted(entry.items()))
        for canonical, entry in sorted(data["canonicals"].items())
    }
    lines = [*SYMBOLS_PY_HEADER]
    lines.extend(
        [
            "from __future__ import annotations",
            "",
            "from dataclasses import dataclass",
            "from typing import Final",
            "",
            "",
            "@dataclass(frozen=True)",
            "class RiskProfile:",
            "    max_spread_points: int | None",
            "    max_sl_distance_pct: float",
            "    session_policy: str",
            "",
            "",
            "@dataclass(frozen=True)",
            "class CanonicalSymbol:",
            "    base: str",
            "    quote: str",
            "    group: str",
            "    risk: RiskProfile",
            "",
            "",
            f"REGISTRY_VERSION: Final[int] = {data['version']}",
            "",
            "BROKER_TO_CANONICAL: Final[dict[str, dict[str, str]]] = {",
        ]
    )
    for broker, mapping in brokers.items():
        lines.append(f"    {broker!r}: {{")
        for raw, canonical in mapping.items():
            lines.append(f"        {raw!r}: {canonical!r},")
        lines.append("    },")
    lines.append("}")
    lines.append("")
    lines.append("CANONICALS: Final[dict[str, CanonicalSymbol]] = {")
    for canonical, entry in canonicals.items():
        lines.extend(
            [
                f"    {canonical!r}: CanonicalSymbol(",
                f"        base={entry['base']!r},",
                f"        quote={entry['quote']!r},",
                f"        group={entry['group']!r},",
                "        risk=RiskProfile(",
                f"            max_spread_points={entry['max_spread_points']!r},",
                f"            max_sl_distance_pct={float(entry['max_sl_distance_pct'])!r},",
                f"            session_policy={entry['session_policy']!r},",
                "        ),",
                "    ),",
            ]
        )
    lines.append("}")
    lines.append("")
    atomic_write(PY_OUT_DIR / "symbols.py", "\n".join(lines))


def write_mql5_symbols(data: dict[str, Any]) -> None:
    validate_symbol_registry_data(data)
    broker_items = [
        (broker, raw, canonical)
        for broker, mapping in sorted(data["brokers"].items())
        for raw, canonical in sorted(mapping.items())
    ]
    canonical_items = [
        (canonical, entry) for canonical, entry in sorted(data["canonicals"].items())
    ]
    lines = [*SYMBOLS_MQL5_HEADER]
    lines.extend(
        [
            "#ifndef FARM_SYMBOLS_MQH",
            "#define FARM_SYMBOLS_MQH",
            "",
            "string FarmSymbolCanonical(const string broker, const string raw)",
            "{",
        ]
    )
    for broker, raw, canonical in broker_items:
        lines.append(
            f"   if(broker == {mql_quote(broker)} && raw == {mql_quote(raw)}) "
            f"return {mql_quote(canonical)};"
        )
    lines.extend(["   return \"\";", "}", ""])

    for function, field in [
        ("FarmSymbolBase", "base"),
        ("FarmSymbolQuote", "quote"),
        ("FarmSymbolCorrelationGroup", "group"),
    ]:
        lines.extend([f"string {function}(const string canonical)", "{"])
        for canonical, entry in canonical_items:
            lines.append(
                f"   if(canonical == {mql_quote(canonical)}) "
                f"return {mql_quote(entry[field])};"
            )
        lines.extend(["   return \"\";", "}", ""])

    lines.extend(
        [
            "bool FarmSymbolRisk(const string canonical,",
            "                    int    &out_max_spread_points,",
            "                    double &out_max_sl_distance_pct,",
            "                    string &out_session_policy)",
            "{",
            "   out_max_spread_points = -1;",
            "   out_max_sl_distance_pct = 0.0;",
            "   out_session_policy = \"\";",
        ]
    )
    for canonical, entry in canonical_items:
        spread = -1 if entry["max_spread_points"] is None else int(entry["max_spread_points"])
        lines.extend(
            [
                f"   if(canonical == {mql_quote(canonical)})",
                "   {",
                f"      out_max_spread_points = {spread};",
                f"      out_max_sl_distance_pct = {float(entry['max_sl_distance_pct'])!r};",
                f"      out_session_policy = {mql_quote(entry['session_policy'])};",
                "      return true;",
                "   }",
            ]
        )
    lines.extend(["   return false;", "}", ""])

    lines.extend(["bool FarmSymbolProductionReady(const string canonical)", "{"])
    for canonical, entry in canonical_items:
        ready = "true" if entry["max_spread_points"] is not None else "false"
        lines.append(f"   if(canonical == {mql_quote(canonical)}) return {ready};")
    lines.extend(["   return false;", "}", "", "#endif", ""])
    atomic_write(MQL5_OUT_DIR / "FarmSymbols.mqh", "\n".join(lines))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.parse_args(argv)
    schemas = load_schemas()
    symbols_data = load_symbol_registry_data(SYMBOLS_FILE)
    write_python_models(schemas)
    write_mql5_models(schemas)
    write_python_symbols(symbols_data)
    write_mql5_symbols(symbols_data)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
